services:
  db:
    image: postgis/postgis:17-master
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - cablesv2_net

  backend:
    volumes:
      - backend_media:/app/uploads
      - backend_static:/app/static
    networks:
      - cablesv2_net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    ports:
      - 80:80
    volumes:
      - backend_static:/usr/share/nginx/html/static
    networks:
      - front
      - cablesv2_net

volumes:
  backend_static:
  backend_media:
  db_data:

networks:
  front:
    external: true
  cablesv2_net:
    driver: bridge
