services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    volumes:
      - media:/app/uploads
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      backend:
        condition: service_healthy

volumes:
  media:
